parameters:
- name: windows
  type: boolean
  default: false

steps:
- script: |
    which python
    python -V
  displayName: Check Python $(python.version) path

- script: python -m pip install --user -U pytest pytest-cov coverage codecov
  displayName: Install test dependencies

- ${{ if eq(parameters.windows, true) }}:

  - script: |
      set PYORC_DEBUG=1
      python -m pip install -vvv --user .
    displayName: Install package

  - script: |
      FOR /F "tokens=* USEBACKQ" %%F IN (`python -c "import os, pyorc; print(os.path.dirname(pyorc.__file__))"`) DO (SET INSTALLDIR=%%F)
      echo %INSTALLDIR%
      python -m pytest -vs --junitxml=./test-results.xml --cov=%INSTALLDIR% tests/
    displayName: Run pytest (Windows)

- ${{ else }}:

  - script: |
      PYORC_DEBUG=1 CFLAGS="-coverage" python -m pip install -vvv --user .
    displayName: Install package

  - script: |
      INSTALLDIR=$(python -c "import os, pyorc; print(os.path.dirname(pyorc.__file__))")
      echo $INSTALLDIR
      python -m pytest -vs --junitxml=./test-results.xml --cov="$INSTALLDIR" tests/
    displayName: Run pytest (Unix)

- task: PublishTestResults@2
  inputs:
    testResultsFiles: test-results.xml
    testRunTitle: Tests on $(Agent.OS) with Python $(python.version)
  condition: succeededOrFailed()

- script: python -m codecov
  env:
    CODECOV_TOKEN: $(codecov)
  displayName: Report Coverage
  condition: succeeded()
